import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {FileBlob,PresentationFile} from '@oai/artifact-tool';
import sharp from 'sharp';
const root='D:/GALATICX/masterhub_iot_noushith', build=root+'/artifacts/ppt_build', skill='C:/Users/NOUSHITH/.codex/plugins/cache/openai-primary-runtime/presentations/26.904.11930/skills/presentations';
const {makeNativeBulletParagraphs,finalizePresentation}=await import(pathToFileURL(skill+'/container_tools/artifact_tool_utils.mjs'));
const p=await PresentationFile.importPptx(await FileBlob.load('D:/IEEE/REPORT/noushith_IOT_ppt.pptx'));
const originals=[...p.slides.items], base=originals[1], out=[];
for(const layout of [...p.layouts.items,...p.masters.items]){
 for(const sh of [...layout.shapes.items]){
  if(sh.placeholder?.type==='slideNumber'||String(sh.text).includes('‹#›'))layout.shapes.deleteById(sh.id);
 }
}
const green='#087F46', ink='#25332B';
function txt(s,t,x,y,w,h,size=23,color=ink,bold=false,align='left'){
 const a=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});
 a.text=t;a.text.style={typeface:'Arial',fontSize:size,color,bold,alignment:align,autoFit:'none'};return a;
}
function slide(title,source='README.md'){
 const s=base.duplicate();s.moveTo(p.slides.items.length-1);s.shapes.deleteAll();out.push(s);
 txt(s,title.toUpperCase(),65,23,738,43,28,'#FFFFFF',true,'center');
 txt(s,String(out.length),894,679,44,23,12,'#666666','', 'right');
 s.speakerNotes.textFrame.setText('Sources: '+source+'\nRepository snapshot: 26 September 2026. Implementation describes code and mappings. Screenshots show the current local application, with external hardware disconnected.');return s;
}
function list(s,items,x=85,y=160,w=775,h=420,size=25){const a=txt(s,'',x,y,w,h,size);a.text=makeNativeBulletParagraphs(items,{marginLeftPoints:18,hangingPoints:9,spaceAfterPoints:15});return a;}
function heading(s,t,y=116){txt(s,t,85,y,780,46,27,green,true);}
function footer(s,t){txt(s,t,85,603,775,55,17,'#526557');}
function two(title,left,right,source){let s=slide(title,source);txt(s,left[0],85,130,360,38,25,green,true);txt(s,right[0],500,130,360,38,25,green,true);list(s,left[1],85,185,345,375,23);list(s,right[1],500,185,345,375,23);return s;}
async function img(s,file,x=78,y=112,w=802,h=477){s.images.add({blob:new Uint8Array(await fs.readFile(file)),contentType:'image/png',position:{left:x,top:y,width:w,height:h},fit:'contain',alt:path.basename(file)});}
async function crop(file,name,box){await sharp(build+'/'+file).extract(box).png().toFile(build+'/'+name);return build+'/'+name;}
// Crop screenshots only to keep UI evidence readable on a 4:3 slide.
const meta=await sharp(build+'/fresh-full.png').metadata();
const captureWidth=1025;
const overview=await crop('fresh-full.png','screen-overview.png',{left:15,top:0,width:captureWidth-50,height:Math.min(900,meta.height)});
const desktopMeta=await sharp(build+'/fresh-desktop-full.png').metadata();
const desktop=await crop('fresh-desktop-full.png','screen-desktop.png',{left:20,top:365,width:captureWidth-55,height:Math.min(620,desktopMeta.height-365)});
const commandMeta=await sharp(build+'/fresh-command-full.png').metadata();
const command=await crop('fresh-command-full.png','screen-command.png',{left:20,top:365,width:captureWidth-55,height:Math.min(620,commandMeta.height-365)});
const bciMeta=await sharp(build+'/fresh-bci.png').metadata();
const bci=await crop('fresh-bci.png','screen-bci.png',{left:Math.max(0,bciMeta.width-470),top:0,width:Math.min(470,bciMeta.width),height:bciMeta.height});
const sidebar=await crop('fresh-sidebar.png','screen-sidebar.png',{left:0,top:0,width:380,height:(await sharp(build+'/fresh-sidebar.png').metadata()).height});

// Preserve the original photographic cover and institute artwork.
const cover=originals[0].duplicate();cover.moveTo(p.slides.items.length-1);out.push(cover);
const coverShapes=cover.shapes.items;
coverShapes.find(x=>String(x.text).includes('SYNAPTIMESH')).text='MASTERHUB\nIMPLEMENTATION REVIEW';
const ct=coverShapes.find(x=>String(x.text).includes('MASTERHUB\n'));ct.position={left:76,top:203,width:650,height:100};ct.text.style={typeface:'Times New Roman',fontSize:34,bold:true,color:'#FFFFFF',autoFit:'none'};
coverShapes.find(x=>String(x.text).includes('IoT Hardware')).text='BCI  /  IoT  /  Desktop  /  Embedded Mobility  /  Media';
coverShapes.find(x=>String(x.text).includes('2026')).text='CURRENT IMPLEMENTATION  /  SEPTEMBER 2026';
cover.speakerNotes.textFrame.setText('Original cover artwork and presenter identity preserved from noushith_IOT_ppt.pptx. Current implementation as of 26 September 2026.');

let s=slide('Presentation overview');list(s,['Project background and current implementation scope','Architecture, state machine and gesture navigation','Desktop, IoT, mobility and media workflows','Cortex BCI connection and temporal control','Current dashboard, connectivity and diagnostics','Implemented outputs, test coverage and next steps'],85,130,780,475,25);
s=slide('Abstract and project scope');heading(s,'One control hub for multiple execution domains');list(s,['MasterHub accepts browser controls, arrow keys, API commands and classified mental commands from EMOTIV Cortex.','The Flask application maintains context, resolves command mappings and dispatches actions through dedicated handlers.','The current project connects desktop applications, IoT relay devices, mobility hardware and desktop or mobile media workflows.','The original IoT work remains part of the wider SynaptiMesh project.'],85,182,775,385,24);
s=two('Original project and current MasterHub',['Previous presentation',['ESP32 gateway and Arduino Nano sensing','LoRa communication and relay control','Light, fan, pump and audio outputs','MQTT integration and command acknowledgements']],['Current repository',['Four control domains in one dashboard','17 FSM modes and 98 command routes','Cortex profiles, streaming and mental control','Remote PC, UART and mobile media integration']],'Original PPT slides 3, 7–9; mappings/*.json; README.md');footer(s,'The previous deck records earlier hardware work. Current screenshots document the software interface.');
s=slide('Motivation and objectives');heading(s,'A consistent workflow across different targets');list(s,['Reduce separate control interfaces for desktop applications and physical devices.','Reuse a small mental-command vocabulary through context-sensitive menus.','Expose the active domain, device, target and pending command before execution.','Track connection state and command feedback for troubleshooting.','Keep hardware transport, command mappings and application actions modular.'],85,180,775,390,25);
s=slide('Current implementation inventory','mappings/mode_map.json; command_map.json; workflow_map.json; iot_map.json');
[['4','Control domains'],['11','Workflow targets'],['17','FSM modes'],['98','Command routes']].forEach((a,i)=>{txt(s,a[0],85+i*198,155,170,82,64,green,true);txt(s,a[1],85+i*198,245,175,65,23,ink,true);});list(s,['23 IoT payload mappings include relay actions and firmware maintenance commands.','JSON definitions drive domain navigation and command choices.','Counts describe implemented mappings, not the number of physically connected devices.'],85,380,775,210,24);
s=slide('Overall software architecture','app.py; core/engine.py; core/router.py; services/; actions/');heading(s,'Input, decision and execution layers');list(s,['Input: dashboard, keyboard, REST clients and Cortex mental-command stream.','Decision: input normalization, FSM context, temporal framing and command validation.','Routing: command_map.json selects the execution domain and action identifier.','Execution: application handlers, hardware MQTT, USB serial and mobile MQTT.','Feedback: state snapshots, command outcomes, metrics, logs and device presence.'],85,180,775,385,24);
s=slide('Current dashboard: main console','templates/dashboard.html; static/masterhub.js; current screenshot');await img(s,overview,73,103,814,490);footer(s,'Current local capture. MQTT, USB and BCI show their actual disconnected state.');
s=slide('Domain, device and command workflow','mappings/workflow_map.json; services/workflow_service.py');heading(s,'Three phases share the same state machine');list(s,['Domain selection: Desktop, Embedded Mobility, IoT Smart Home or AI/ML & Media.','Device selection: an application, smart-home output, mobility device or media target.','Command execution: choose an action and supply any required parameters.','Push + Right returns to the previous menu. Push + Left returns to the main menu.','The same gesture has different meanings in different modes.'],85,180,775,400,24);
s=two('Gesture vocabulary and timing',['Navigation',['Push: Desktop at the main menu','Pull: Embedded Mobility','Left: IoT Smart Home','Right: AI/ML & Media','Ordered pairs provide additional commands']],['Timing behavior',['Default window: 4 seconds','Configuration range: 2–10 seconds','Dashboard actions: preview and countdown','Manual command pairs: immediate dispatch','Live BCI pairs: original deadline']],'README.md; static/masterhub.js; cortex/control.py');footer(s,'Direct /api/command requests do not automatically use the browser framing delay.');
s=slide('Desktop domain: application workflows','mappings/workflow_map.json; actions/desktop/');heading(s,'Four application workflows');list(s,['YouTube: previous video, next video, play/pause and search/play.','Chrome: open an article, scroll up or down and Google search.','Notepad: open the application and save a file through mapped commands.','Gmail: compose with recipient, subject and body, then send through a separate command.','Application handlers use the selected Local Host or compatible remote target.'],85,180,775,390,24);
s=slide('Current desktop and target selection','Current dashboard screenshot; core/devices.py');await img(s,desktop,75,105,810,490);footer(s,'The PC Agent Controller separates target selection from the application menu.');
s=slide('Current command execution screen','Current dashboard screenshot; mappings/workflow_map.json');await img(s,command,75,110,810,450);footer(s,'Notepad mode exposes Open and Save file. This capture shows navigation only.');
s=slide('IoT hardware implementation','Original PPT slides 7, 9, 10');heading(s,'Hardware foundation documented in the original project');list(s,['ESP32 gateway connects MQTT commands to relay outputs.','Arduino Nano handles ultrasonic distance and float-switch sensing.','LoRa links the sensor node and gateway through SPI modules.','DFPlayer provides audio status output through a UART connection.','Original relay assignments: pump GPIO 25, light GPIO 21 and fan GPIO 32.'],85,180,775,390,24);footer(s,'Hardware details come from the supplied earlier presentation.');
s=slide('Original IoT wiring reference','Original PPT slide 10');await img(s,build+'/source_render/slide-10.png',100,108,750,493);footer(s,'Retained project wiring reference from your earlier PPT.');
s=slide('Current IoT command integration','mappings/iot_map.json; actions/iot/handler.py; services/mqtt_service.py');heading(s,'Relay control plus device maintenance commands');list(s,['Light, fan and pump workflows expose On and Off choices.','The IoT map translates action names into firmware command strings.','Additional mappings include all_on, all_off, PING and self-test.','OTA_UPDATE and relay-polarity commands exist in the payload map.','MasterHub publishes to the configured broker and reads device status separately.'],85,180,775,390,24);footer(s,'A mapped command requires compatible firmware support on the receiving device.');
s=slide('Embedded mobility implementation','actions/embedded/handler.py; mappings/embedded_map.json; services/workflow_service.py');heading(s,'Robot car and wheelchair use separate control topics');list(s,['Both device menus provide forward, backward, left, right and stop.','Additional mappings support left and right 360-degree rotation.','Handlers translate action identifiers into device-specific payload strings.','Readiness checks combine broker state, matching device identity and fresh status.','BCI motion checks the active direction at dispatch and requests stop after neutral.'],85,180,775,390,24);footer(s,'These are software control capabilities. Physical motion requires connected, verified hardware.');
s=two('Desktop and mobile media',['Desktop JioSaavn',['Browser-based JioSaavn workflow','Next track and previous track','Play/pause and search','Ordered pairs for volume up/down']],['Mobile JioSaavn',['Dedicated Android companion path','Next, previous and play/pause','Android home, search and launch','Phone presence and now-playing feedback']],'mappings/workflow_map.json; actions/media_jiosaavn_mobile.py');
s=slide('Mobile MQTT and acknowledgement','services/mobile_mqtt_service.py; api/jiosaavn.py');heading(s,'The phone uses an independent MQTT service');list(s,['Separate topics carry commands, status, heartbeat, media, acknowledgements and errors.','Dispatch requires a fresh phone heartbeat and remote control enabled on the phone.','Each command carries a unique ID, issue time and expiry time.','The service tracks PENDING, EXECUTED, FAILED, REJECTED, UNCONFIRMED and TIMEOUT results.','Retained online messages cannot establish fresh liveness.'],85,180,775,390,24);footer(s,'Defaults in code: 8-second acknowledgement timeout and 35-second heartbeat timeout.');
s=slide('Cortex connection and trained profiles','cortex/service.py; cortex/auth.py; cortex/session.py; cortex/profile.py');heading(s,'EMOTIV supplies the classified mental commands');list(s,['EMOTIV Launcher and the local Cortex service provide headset access.','MasterHub requests authorization, discovers the headset and opens a session.','The user selects and loads an existing trained mental-command profile.','The com stream provides the detected action and detector power.','MasterHub routes predictions into its controller. It does not train a raw EEG model.'],85,180,775,390,24);
s=slide('Current BCI headset console','templates/bci_panel.html; current screenshot');await img(s,bci,520,108,340,495);heading(s,'Connection and control');list(s,['Connection-stage feedback','Trained-profile selector','Headset, battery and signal fields','Live mental command and power','Monitor mode and control toggle'],85,195,385,365,23);footer(s,'The screenshot preserves the offline state. Credentials remain collapsed.');
s=slide('Live BCI temporal controller','cortex/control.py; simulator/config.py');heading(s,'One frame captures one single or ordered pair');list(s,['A neutral sample rearms control. A qualifying active sample starts the frame.','The default detector-power threshold is 0.20, subject to configuration.','A distinct second gesture joins the first only when that pair exists in the current mode.','Repeated packets of the same held gesture do not create repeated commands.','Singles and valid pairs execute at the original deadline when a new prediction arrives.'],85,180,775,390,24);footer(s,'Detector power is not a measured intention-accuracy percentage.');
s=slide('BCI context and command inputs','cortex/control.py; templates/bci_panel.html; static/bci-panel.js');heading(s,'The controller keeps intent tied to the active workflow');list(s,['Mode or target changes reset pending context. Control-generation checks prevent stale dispatch.','An unassigned qualifying gesture pair cancels its frame.','Search, compose and save operations use prepared parameter fields.','Neutral does not cancel a pending nonmotion action. Stop Control cancels BCI actuation.','Motion requires matching direction at dispatch and neutral requests a stop afterwards.'],85,180,775,390,24);
s=slide('Remote PC agents and USB serial','core/devices.py; services/usb_service.py; artifacts/start_agent.py; README.md');heading(s,'Target selection supports local and external execution');list(s,['Local Host executes supported desktop actions on the MasterHub computer.','Remote PCs register a device ID and use a compatible agent over MQTT or serial.','Agent startup helpers and configuration artifacts support deployment setup.','USB configuration selects a COM port and uses JSON-line messages at 115200 baud by default.','A registered target still needs a running agent, a working transport and fresh presence.'],85,180,775,390,24);
s=slide('Current sidebar and operator tools','templates/dashboard.html; current screenshot');await img(s,sidebar,80,107,310,493);txt(s,'Built-in tools',435,125,390,42,28,green,true);list(s,['Connection matrix and domain shortcuts','Temporal-window presets','Gesture cheat sheet and user guide','Target registration and UART setup','Reset state and software E-Stop'],435,193,370,348,23);footer(s,'The sidebar exposes configuration and diagnostic controls within the main console.');
s=slide('Status, telemetry and activity records','core/metrics.py; services/manual_logger_service.py; services/bci_logger_service.py');heading(s,'Feedback supports diagnosis at each layer');list(s,['Metrics record response, processing and execution latency with up to 100 recent samples.','Counters track total, successful and failed commands.','The Fault Recovery label derives from command outcomes. It is not a physical recovery-time measurement.','Manual and BCI activity records help trace command source and execution result.','The dashboard offers LOG, JSON and CSV telemetry export.'],85,180,775,390,24);
s=slide('API and configuration surface','api/routes.py; api/jiosaavn.py; cortex/dashboard.py');heading(s,'The browser and external clients share the backend');list(s,['POST /api/command accepts supported command and gesture inputs.','State and workflow endpoints expose current context and available choices.','Health, metrics and device-status endpoints support monitoring.','Hardware configuration stores broker and topic settings for subsequent use.','Cortex endpoints manage connection, profile, stream status and control mode.'],85,180,775,390,24);
s=slide('Safety controls and operating boundaries','README.md; cortex/control.py; static/masterhub.js');heading(s,'Software safeguards support controlled testing');list(s,['Command validation rejects unsupported routes and checks required parameters.','The BCI interface begins in monitor mode and requires explicit control enablement.','Dashboard countdowns support cancellation before dispatch.','Software E-Stop requests stops. A device acknowledgement and independent hardware stop remain essential.','Simulation Mode changes UI state and logs. It does not isolate real actions.'],85,180,775,390,24);
s=slide('Test coverage and replay tools','tests/test_cortex_control.py; tests/; simulator/README.md');heading(s,'Tests cover control behavior and service integration');list(s,['BCI tests cover framing, neutral rearm, ordered pairs, context changes and motion handling.','Workflow tests cover state transitions, mappings and command updates.','Other modules test hardware status, mobile media and separate logging paths.','Recorded-prediction replay sends requests through the command API.','Replay filtering differs from the live controller. Hardware results need a connected-device test.'],85,180,775,390,24);footer(s,'This deck describes the test coverage present in the repository, not a new full-suite test result.');
s=two('Implementation status and dependencies',['Implemented in MasterHub',['Four-domain dashboard and workflow builder','Mapped state machine and command router','Cortex stream and temporal controller','MQTT, USB and remote-target services','Mobile acknowledgements and telemetry']],['Needed for live operation',['Broker and compatible device firmware','Connected and safe mobility hardware','Running remote PC or Android agent','EMOTIV access and trained profile','Application sessions and desktop access']],'README.md; services/; cortex/; actions/');
s=slide('Future development priorities');heading(s,'Next work builds on the current modules');list(s,['Complete connected-device validation for each transport and command family.','Add device-side watchdogs and verify stop acknowledgements under link failure.','Create a dry-run backend that cannot dispatch physical or desktop actions.','Expand repeatable integration tests and remote-agent packaging.','Improve user-specific BCI calibration and deployment authentication.'],85,180,775,390,24);footer(s,'Proposed next steps, separate from implemented features.');
s=slide('Conclusion');heading(s,'MasterHub now provides a common control workflow');list(s,['The project combines the earlier IoT hardware work with desktop, mobility and media control.','A shared state machine and mapping layer reuse manual and mental-command inputs.','The current dashboard exposes workflow context, connection status and command feedback.','The next milestone is repeatable end-to-end validation with the complete hardware setup.'],85,182,775,360,26);
const end=originals[13].duplicate();end.moveTo(p.slides.items.length-1);out.push(end);
txt(cover,'1',894,679,44,23,12,'#666666',false,'right');
txt(end,String(out.length),894,679,44,23,12,'#666666',false,'right');
// Remove only imported working copies after their artwork has been reused.
for(const old of originals)old.delete();
out.forEach((x,i)=>x.moveTo(i));
await fs.mkdir(root+'/artifacts/presentation_output',{recursive:true});
const candidatePath=build+'/masterhub-rebuilt-candidate.pptx';
await(await PresentationFile.exportPptx(p)).save(candidatePath);
const finalPath=root+'/artifacts/presentation_output/MasterHub_Complete_Implementation.pptx';
const result=await finalizePresentation({workspaceDir:root,candidatePath,finalPath,pythonExecutable:'C:/Users/NOUSHITH/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',integrityValidatorPath:skill+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:skill+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','9144000,6858000','--validate-bullet-geometry','--validate-heading-fit'],explicitTotalSlideCount:out.length,requiredNativeTableOwnerSlides:[],requiredNativeChartOwnerSlides:[],sourceTemplatePath:'D:/IEEE/REPORT/noushith_IOT_ppt.pptx',verifyArtifactToolImport:true,receiptPath:build+'/complete-validation.json'});
console.log(JSON.stringify({slides:out.length,finalPath:result.finalPath}));
